# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

use_frameworks!

target 'BowlingGame' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  
  # Pods for BowlingGame
  
  target 'BowlingGameTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
    
  end

end
